"""added user birth and phone

Revision ID: 200934e72e95
Revises: dfe96a9175b2
Create Date: 2026-02-09 16:39:51.489465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200934e72e95'
down_revision: Union[str, Sequence[str], None] = 'dfe96a9175b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'birth')
    # ### end Alembic commands ###
