"""restaurant table revisioned

Revision ID: 5f014dfcedf5
Revises: 4abef5a859eb
Create Date: 2026-02-04 13:51:51.765971

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f014dfcedf5"
down_revision: Union[str, Sequence[str], None] = "4abef5a859eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "restaurants", sa.Column("unique_hash", sa.String(length=64), nullable=False)
    )
    op.add_column("restaurants", sa.Column("latitude", sa.Float(), nullable=True))
    op.add_column("restaurants", sa.Column("longitude", sa.Float(), nullable=True))
    op.add_column(
        "restaurants",
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_restaurants_naver_id"), table_name="restaurants")
    op.drop_constraint(op.f("restaurants_naver_id_key"), "restaurants", type_="unique")
    op.create_index(
        op.f("ix_restaurants_unique_hash"), "restaurants", ["unique_hash"], unique=True
    )
    op.drop_column("restaurants", "naver_id")
    op.drop_column("restaurants", "mapy")
    op.drop_column("restaurants", "name")
    op.drop_column("restaurants", "mapx")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "restaurants",
        sa.Column("mapx", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "restaurants",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.add_column(
        "restaurants",
        sa.Column("mapy", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "restaurants",
        sa.Column("naver_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_restaurants_unique_hash"), table_name="restaurants")
    op.drop_index(
        "idx_restaurants_location", table_name="restaurants", postgresql_using="gist"
    )
    op.create_unique_constraint(
        op.f("restaurants_naver_id_key"),
        "restaurants",
        ["naver_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_restaurants_naver_id"), "restaurants", ["naver_id"], unique=True
    )
    op.drop_column("restaurants", "location")
    op.drop_column("restaurants", "longitude")
    op.drop_column("restaurants", "latitude")
    op.drop_column("restaurants", "unique_hash")
    # ### end Alembic commands ###
