"""add restaurant imageurl col

Revision ID: d9bccef64db3
Revises: d4f6dec23846
Create Date: 2026-03-04 14:37:08.083707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9bccef64db3'
down_revision: Union[str, Sequence[str], None] = 'd4f6dec23846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'image_url')
    # ### end Alembic commands ###
