"""added restaurant name at table

Revision ID: dfe96a9175b2
Revises: 5f014dfcedf5
Create Date: 2026-02-04 16:43:43.442016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe96a9175b2'
down_revision: Union[str, Sequence[str], None] = '5f014dfcedf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'name')
    # ### end Alembic commands ###
