"""Updated restaurants models

Revision ID: f9efed7b8052
Revises: 200934e72e95
Create Date: 2026-02-10 13:49:57.999325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9efed7b8052'
down_revision: Union[str, Sequence[str], None] = '200934e72e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('kakao_place_id', sa.String(length=50), nullable=False))
    op.add_column('restaurants', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('restaurants', sa.Column('place_url', sa.String(length=255), nullable=True))
    op.add_column('restaurants', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('restaurants', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('restaurants', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('restaurants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_restaurants_unique_hash'), table_name='restaurants')
    op.create_index(op.f('ix_restaurants_kakao_place_id'), 'restaurants', ['kakao_place_id'], unique=True)
    op.create_index(op.f('ix_restaurants_name'), 'restaurants', ['name'], unique=False)
    op.drop_column('restaurants', 'unique_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('unique_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_restaurants_name'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_kakao_place_id'), table_name='restaurants')
    op.create_index(op.f('ix_restaurants_unique_hash'), 'restaurants', ['unique_hash'], unique=True)
    op.alter_column('restaurants', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('restaurants', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('restaurants', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('restaurants', 'updated_at')
    op.drop_column('restaurants', 'place_url')
    op.drop_column('restaurants', 'phone')
    op.drop_column('restaurants', 'kakao_place_id')
    # ### end Alembic commands ###
